from-scratch documentation, pic-rs compile notes now recommend using non-privileged account, but…
LemmyNet/lemmy-docs pull request #255
Opened 2023-07-19 21:03 UTC by RocketDerp

…there are still missing steps in this document. Trying to clean up problems as they are spotted so it does not get so far behind.

2023-07-28 20:16 UTC, RocketDerp commented
EMERGENCY change to documentation committed regarding 0.18.3 release.

2023-08-01 10:39 UTC, Nutomic commented on src/administration/from_scratch.md
> +Depending on preference, pict-rs can be installed as a standalone application, or it can be embedded within Lemmy itself (see below). In both cases, pict-rs requires the `magick` command which comes
Postgres 15 is required since Lemmy version 0.17

https://join-lemmy.org/news/2023-01-31_-_Lemmy_Release_v0.17.0

2023-08-01 10:39 UTC, Nutomic commented on src/administration/from_scratch.md
> +IMPORTANT NOTE: Ubuntu 20.04 comes with PostgreSQL 13.x, and Lemmy 0.18.3 and later requires newer versions. It may be best to consult Lemmy support forums on the topic of ugprades using From Scratch
Postgres 15 is required since Lemmy version 0.17

https://join-lemmy.org/news/2023-01-31_-_Lemmy_Release_v0.17.0

2023-08-04 14:48 UTC, dessalines requested changes

2023-08-04 14:48 UTC, dessalines commented on src/contributors/02-local-development.md
> +If you are working on the PostgreSQL schema and database statements, cargo `install diesel_cli` gives you [a way to work with the migrations from a shell](https://github.com/diesel-rs/diesel/tree/mas
`cargo install diesel_cli` , that whole command should be in the code ticks.

2023-09-06 17:07 UTC, closed without merging