feat: Introducing Elestio as fully managed deployment option
LemmyNet/lemmy-docs pull request #277
Opened 2023-10-17 12:58 UTC by kaiwalyakoparkar

closes #276

2023-10-18 06:17 UTC, kaiwalyakoparkar commented
@Nutomic Thank you so much for your suggestion. I have made the changes as requested. Also as you get chance, kindly take a look at the proposed collaboration opportunity in #277 🙌

2023-10-18 15:15 UTC, dessalines requested changes

2023-10-18 15:15 UTC, dessalines commented on src/SUMMARY.md
> +- [Install on Elestio](adminitstration/)
Mispelled. Make sure you test this.

2023-10-18 15:15 UTC, dessalines commented on src/administration/administration.md
> +### Managed Hostings
Hopefully this will fail the prettier CI check.

2023-10-19 13:07 UTC, Nutomic commented on src/SUMMARY.md
> +- [Install on Elestio](administration/)
You can get rid of this line as its part of the existing administration page now which is already linked.

2023-10-19 13:42 UTC, Nutomic approved these changes

2023-10-20 03:17 UTC, dessalines approved these changes

2023-10-20 08:54 UTC, merged