improve descriptions for searching for federation
LemmyNet/lemmy-docs pull request #41
Opened 2021-03-12 00:32 UTC by xundeenergie

As discussed in matrix, i wrote an improvement for the docu for searching for communities, posts and comments.

2021-03-12 00:53 UTC, Nutomic commented on src/en/federation/federation.md
> +You can copy the URL of the community from the address-bar in your browser and insert it in your search-field. Wait a few seconds, the post will appear below. There is no indicator for a running sear
For comments, the format is `https://lemmy.ml/comment/456`, so you cant copy it directly and have to remove  the `/post/123` part first.

2021-03-12 00:54 UTC, Nutomic commented on src/en/federation/federation.md
> +- edited comments and posts
This is not a complete list, but its enough for here. Maybe add "mod actions" as a general category.

2021-03-12 00:55 UTC, Nutomic commented on src/en/federation/federation.md
> +## Searching for communities
Searching isnt really the right term. "Fetching" is more accurate.

2021-03-12 00:56 UTC, Nutomic commented on src/en/federation/federation.md
> +
Users can also be fetched by URL, but that currently doesnt fetch any further data.

2021-03-12 00:57 UTC, Nutomic commented on src/en/federation/federation.md
> +Copy the URL of a post in your lemmy's search-field. Wait a few seconds until the post will appear. Klick on it, you'll be lead to the posting into the community, where you cann see the "Follow"-butt
That part about the follow button is confusing, dont think it belongs here.

2021-03-12 00:58 UTC, Nutomic commented on src/en/federation/federation.md
> +There is no possibility to fetch easily old postings or comments from a remote instance from your instance, if you have joined a community.
Calling it "limitation" would sound a bit nicer ;)

2021-03-12 15:09 UTC, dessalines requested changes

2021-03-12 15:09 UTC, dessalines commented on src/en/federation/federation.md
> +https://lemmy.ml/u/20776
Whats this line about also.

2021-03-12 15:09 UTC, dessalines commented on src/en/federation/federation.md
> +Updates mean:
Always use 2 newlines for new paragraphs for lines.

2021-03-12 15:09 UTC, dessalines commented on src/en/federation/federation.md
> +- new posts
Always add 2 newlines before lists.

2021-03-12 15:09 UTC, dessalines commented on src/en/federation/federation.md
> +This comment, all parent comments, users and community and the responding posting is fetched from the remote instance, if they are not known locally.
Same newline stuff as above.

2021-03-19 12:50 UTC, Nutomic commented
@xundeenergie Are you still planning to update this PR? If not, I can make the necessary changes.

2021-03-24 15:59 UTC, Nutomic commented
I'm finishing this in https://github.com/LemmyNet/lemmy-docs/pull/46.

2021-03-24 15:59 UTC, closed without merging